title:       ING Lab
tagline:     ING Lab @ SKKU
description: Intelligent Narrative and Game Lab

url:     https://inglab.github.io
baseurl: ""

author:
  name:  Yun-Gyung Cheong
  email: aimecca@skku.edu

nav:
  - title: Publications
    url:   /publications/
  - title: Members
    url:   /members/
  - title: Projects
    url:   /projects/
  - title: Courses
    url:   /courses/
  - title: Resources
    url:   /resources/
  - title: References
    url:   /references/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty
